/**
 * Creates an object with the same values as object and keys generated by running each own enumerable string keyed property through iteratee
 * @param obj - The object to iterate over
 * @param iteratee - The function invoked per iteration
 * @returns Returns the new mapped object
 * @example
 * mapKeys({ a: 1, b: 2 }, (value, key) => key + value); // { 'a1': 1, 'b2': 2 }
 */
export function mapKeys<T extends object, K extends string | number | symbol>(
  obj: T,
  iteratee: (value: T[keyof T], key: keyof T, obj: T) => K
): Record<K, T[keyof T]> {
  if (obj == null) {
    return {} as Record<K, T[keyof T]>;
  }

  const result = {} as Record<K, T[keyof T]>;

  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) {
      const newKey = iteratee(obj[key], key as keyof T, obj);
      result[newKey] = obj[key];
    }
  }

  return result;
}