/**
 * Creates an object with the same keys as object and values generated by running each own enumerable string keyed property through iteratee
 * @param obj - The object to iterate over
 * @param iteratee - The function invoked per iteration
 * @returns Returns the new mapped object
 * @example
 * mapValues({ a: 1, b: 2 }, (value) => value * 2); // { a: 2, b: 4 }
 */
export function mapValues<T extends object, U>(
  obj: T,
  iteratee: (value: T[keyof T], key: keyof T, obj: T) => U,
): Record<keyof T, U> {
  if (obj == null) {
    return {} as Record<keyof T, U>;
  }

  const result = {} as Record<keyof T, U>;

  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) {
      result[key as keyof T] = iteratee(obj[key], key as keyof T, obj);
    }
  }

  return result;
}
