import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Tutorial sidebar
  tutorialSidebar: [
    'intro',
    'installation',
    'usage',
    'typescript',
    {
      type: 'category',
      label: 'Examples',
      items: ['examples/intro', 'examples/common-patterns', 'examples/best-practices'],
      collapsed: false,
    },
  ],

  // API sidebar - Auto-generated from docs/api subdirectories
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
